# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from . import thermo_pb2 as thermo__pb2


class TemperatureServerStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getTemperature = channel.unary_stream(
                '/TemperatureServer/getTemperature',
                request_serializer=thermo__pb2.TemperatureRequest.SerializeToString,
                response_deserializer=thermo__pb2.TemperatureReply.FromString,
                )


class TemperatureServerServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getTemperature(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getTemperature': grpc.unary_stream_rpc_method_handler(
                    servicer.getTemperature,
                    request_deserializer=thermo__pb2.TemperatureRequest.FromString,
                    response_serializer=thermo__pb2.TemperatureReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TemperatureServer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperatureServer(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/TemperatureServer/getTemperature',
            thermo__pb2.TemperatureRequest.SerializeToString,
            thermo__pb2.TemperatureReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
