# FROM latonaio/l4t:latest
# FROM latonaio/stream-usb-thermo-by-grpc-base:latest
FROM stream-usb-thermo-by-grpc-base:latest

# Definition of a Device & Service
ENV POSITION=Runtime \
    SERVICE=stream-usb-thermo-by-grpc-client \
    AION_HOME=/var/lib/aion

WORKDIR ${AION_HOME}

# Setup Directoties
RUN mkdir -p \
    $POSITION/$SERVICE
WORKDIR ${AION_HOME}/$POSITION/$SERVICE/

ADD . .

RUN python3 setup-client.py install

CMD ["/bin/sh", "docker-entrypoint-client.sh"]
# ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
