# FROM latonaio/stream-usb-thermo-by-grpc-base:latest
FROM stream-usb-thermo-by-grpc-base:latest

# Definition of a Device & Service
ENV POSITION=Runtime \
    SERVICE=stream-usb-thermo-by-grpc-server \
    AION_HOME=/var/lib/aion \
    PKG_VERSION=8.3.0

WORKDIR ${AION_HOME}
# Setup Directoties
RUN mkdir -p \
    $POSITION/$SERVICE
WORKDIR ${AION_HOME}/$POSITION/$SERVICE/

RUN apt-get update && apt-get install -y \
    gcc \
    cmake \
    libusb-1.0-0-dev \
    build-essential \
    freeglut3 \
    freeglut3-dev \
    libudev-dev \
    libc-bin \
    libcanberra-gtk*

RUN curl -O http://ftp.evocortex.com/libirimager-${PKG_VERSION}-arm64.deb && \
    dpkg --unpack libirimager-8.3.0-arm64.deb && \
    rm /var/lib/dpkg/info/libirimager.postinst && \
    dpkg --configure libirimager && \
    ldconfig

RUN ir_download_calibration

ADD . .
ADD config/generic.xml ${AION_HOME}/${Runtime}/${SERVICE}_1/
RUN python3 setup-server.py install

CMD ["/bin/sh", "docker-entrypoint-server.sh"]
# ENTRYPOINT ["/bin/sh", "-c", "while :; do sleep 10; done"]
