# FROM latonaio/l4t:latest
FROM latonaio/l4t-ds-opencv-7.2:latest

# Definition of a Device & Service
ENV POSITION=Runtime \
    SERVICE=stream-usb-thermo-by-grpc \
    AION_HOME=/var/lib/aion \
    PKG_VERSION=8.3.0

RUN mkdir ${AION_HOME}
WORKDIR ${AION_HOME}
# Setup Directoties
RUN mkdir -p \
    $POSITION/$SERVICE
WORKDIR ${AION_HOME}/$POSITION/$SERVICE/

ADD requirements.txt .
RUN export GRPC_PYTHON_BUILD_EXT_COMPILER_JOBS=8 && pip3 install -r requirements.txt

