# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: thermo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='thermo.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0cthermo.proto\"\x14\n\x12TemperatureRequest\"J\n\x10TemperatureReply\x12\r\n\x05image\x18\x01 \x01(\t\x12\x14\n\x0ctemperatures\x18\x02 \x01(\t\x12\x11\n\ttimestamp\x18\x03 \x01(\t2Q\n\x11TemperatureServer\x12<\n\x0egetTemperature\x12\x13.TemperatureRequest\x1a\x11.TemperatureReply\"\x00\x30\x01\x62\x06proto3'
)




_TEMPERATUREREQUEST = _descriptor.Descriptor(
  name='TemperatureRequest',
  full_name='TemperatureRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=16,
  serialized_end=36,
)


_TEMPERATUREREPLY = _descriptor.Descriptor(
  name='TemperatureReply',
  full_name='TemperatureReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='TemperatureReply.image', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temperatures', full_name='TemperatureReply.temperatures', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='TemperatureReply.timestamp', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=112,
)

DESCRIPTOR.message_types_by_name['TemperatureRequest'] = _TEMPERATUREREQUEST
DESCRIPTOR.message_types_by_name['TemperatureReply'] = _TEMPERATUREREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TemperatureRequest = _reflection.GeneratedProtocolMessageType('TemperatureRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREREQUEST,
  '__module__' : 'thermo_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureRequest)
  })
_sym_db.RegisterMessage(TemperatureRequest)

TemperatureReply = _reflection.GeneratedProtocolMessageType('TemperatureReply', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREREPLY,
  '__module__' : 'thermo_pb2'
  # @@protoc_insertion_point(class_scope:TemperatureReply)
  })
_sym_db.RegisterMessage(TemperatureReply)



_TEMPERATURESERVER = _descriptor.ServiceDescriptor(
  name='TemperatureServer',
  full_name='TemperatureServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=114,
  serialized_end=195,
  methods=[
  _descriptor.MethodDescriptor(
    name='getTemperature',
    full_name='TemperatureServer.getTemperature',
    index=0,
    containing_service=None,
    input_type=_TEMPERATUREREQUEST,
    output_type=_TEMPERATUREREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TEMPERATURESERVER)

DESCRIPTOR.services_by_name['TemperatureServer'] = _TEMPERATURESERVER

# @@protoc_insertion_point(module_scope)
